/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package action;

import java.awt.event.ActionListener;

/**
 *
 * @author Footdua
 */
public class PanelAction extends javax.swing.JPanel {

    /**
     * Creates new form PanelAction
     */
    public PanelAction() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        actionButton = new javax.swing.JButton();

        jButton1.setText("jButton1");

        actionButton.setBackground(new java.awt.Color(51, 153, 255));
        actionButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        actionButton.setForeground(new java.awt.Color(0, 0, 0));
        actionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/detailcon.png"))); // NOI18N
        actionButton.setText("DETAIL");
        actionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(actionButton)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(actionButton)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void actionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionButtonActionPerformed
        // TODO add your handling code here:
        System.out.println("Button clicked!");
        System.out.println("ITWORKKKKKK");
    }//GEN-LAST:event_actionButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton actionButton;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables

}
