package gui;

import com.google.protobuf.TextFormat.ParseException;
import controller.DataUpdate;
import database.Database;
import entitas.DataDiri;
import entitas.Pengajuan;
import entitas.RiwayatSurat;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Arrays;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import java.util.ArrayList;
import java.util.List;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class MahasiswaInterface extends javax.swing.JFrame {
    final Database database;
    private final String roleChecker;
    private CardLayout cardLayout;
    private RiwayatSurat riwayatSurat;
    private String mahasiswaNIM;
    private String peruntukan;
    private String mahasiswaNim;
    private byte[] imageData;
    private String checkNim;
    private JPanel suratButtonPanel;
    /**
     * Creates new form MahasiswaInterface
     * @param roleChecker
     */
    
    public MahasiswaInterface(String roleChecker) {
        initComponents();
        database = new Database();
        this.roleChecker = roleChecker;
        welcomePage();
        initializePanels();
    }
    
    private void initializePanels() {
        riwayatSurat = new RiwayatSurat();
        
        pnlCards.add(welcomePanel, "pnlCard1");
        pnlCards.add(profilPanel, "pnlCard2");
        pnlCards.add(suratPanel, "pnlCard3");
        pnlCards.add(buatPanel, "pnlCard4");
        pnlCards.add(hidePanel, "pnlCard5");
        
        Navigation.setPreferredSize(new Dimension(50, 520));
        Navigation.setVisible(true);
        cardLayout = (CardLayout) pnlCards.getLayout();
        suratButtonPanel = new JPanel();
        
        peruntukanField.setForeground(Color.GRAY);
        peruntukanField.setText("Silahkan mengisi peruntukkan surat");
        peruntukanField.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (peruntukanField.getText().equals("Silahkan mengisi peruntukkan surat")) {
                    peruntukanField.setText("");
                    peruntukanField.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (peruntukanField.getText().isEmpty()) {
                    peruntukanField.setText("Silahkan mengisi peruntukkan surat");
                    peruntukanField.setForeground(Color.GRAY);
                }
            }
        });

        showData(); // Ensure this method is called after setting the FocusListener
    }
    
     public void setPeruntukan(String peruntukan) {
        this.peruntukan = peruntukan;
    }

    public void setMahasiswaNim(String mahasiswaNim) {
        this.mahasiswaNim = mahasiswaNim;
    }

    public void setCheckNim(String checkNim) {
        this.checkNim = checkNim;
    }
        
    private void showTable() {
        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("ID Surat");
        model.addColumn("Jenis Surat");
        model.addColumn("Status");
        model.addColumn("Posisi Surat");
        model.addColumn("Action");
        
        List<String[]> riwayatSuratData = riwayatSurat.readData();

        for (String[] row : riwayatSuratData) {
            model.addRow(row);
        }
        suratTabel.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        Navigation = new javax.swing.JPanel();
        home = new javax.swing.JButton();
        surat = new javax.swing.JButton();
        profil = new javax.swing.JButton();
        orangePanel = new javax.swing.JPanel();
        navButton = new javax.swing.JButton();
        mahasiswaText = new javax.swing.JLabel();
        signOut = new javax.swing.JButton();
        pnlCards = new javax.swing.JPanel();
        welcomePanel = new javax.swing.JPanel();
        showName = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        suratPanel = new javax.swing.JPanel();
        buatSuratButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        suratTabel = new javax.swing.JTable();
        profilPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        saveData = new javax.swing.JButton();
        firstName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lastName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        studyProgram = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        gpaPoint = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        phoneNumber = new javax.swing.JTextField();
        emailUser = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        enrollYear = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        semesterYear = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        placeBirth = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        dayCombo = new javax.swing.JComboBox<>();
        monthCombo = new javax.swing.JComboBox<>();
        yearCombo = new javax.swing.JComboBox<>();
        addressPlace = new javax.swing.JTextField();
        studyLevel = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        buatPanel = new javax.swing.JPanel();
        pilihSurat = new javax.swing.JComboBox<>();
        buatSurat = new javax.swing.JButton();
        peruntukanField = new javax.swing.JTextField();
        hidePanel = new javax.swing.JPanel();
        successfullyPop = new javax.swing.JOptionPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(960, 640));
        setMinimumSize(new java.awt.Dimension(960, 640));
        setPreferredSize(new java.awt.Dimension(960, 663));
        setSize(new java.awt.Dimension(960, 640));

        background.setBackground(new java.awt.Color(204, 204, 204));
        background.setMaximumSize(new java.awt.Dimension(960, 592));
        background.setPreferredSize(new java.awt.Dimension(960, 578));

        Navigation.setBackground(new java.awt.Color(204, 204, 204));
        Navigation.setMaximumSize(new java.awt.Dimension(110, 520));
        Navigation.setMinimumSize(new java.awt.Dimension(10, 520));
        Navigation.setName(""); // NOI18N
        Navigation.setPreferredSize(new java.awt.Dimension(50, 520));
        Navigation.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        home.setBackground(new java.awt.Color(51, 51, 51));
        home.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        home.setForeground(new java.awt.Color(51, 51, 51));
        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/dashIcon.png"))); // NOI18N
        home.setText("Home");
        home.setBorderPainted(false);
        home.setContentAreaFilled(false);
        home.setIconTextGap(15);
        home.setInheritsPopupMenu(true);
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        Navigation.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 130, -1));

        surat.setBackground(new java.awt.Color(51, 51, 51));
        surat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        surat.setForeground(new java.awt.Color(51, 51, 51));
        surat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/messageIcon.png"))); // NOI18N
        surat.setText("Surat");
        surat.setBorderPainted(false);
        surat.setContentAreaFilled(false);
        surat.setIconTextGap(16);
        surat.setInheritsPopupMenu(true);
        surat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suratActionPerformed(evt);
            }
        });
        Navigation.add(surat, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 80, 140, -1));

        profil.setBackground(new java.awt.Color(51, 51, 51));
        profil.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        profil.setForeground(new java.awt.Color(51, 51, 51));
        profil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/profilIcon.png"))); // NOI18N
        profil.setText("Profil");
        profil.setBorderPainted(false);
        profil.setContentAreaFilled(false);
        profil.setIconTextGap(15);
        profil.setInheritsPopupMenu(true);
        profil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilActionPerformed(evt);
            }
        });
        Navigation.add(profil, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 40, 140, -1));

        orangePanel.setBackground(new java.awt.Color(255, 153, 51));
        orangePanel.setMaximumSize(new java.awt.Dimension(970, 60));
        orangePanel.setName(""); // NOI18N

        navButton.setBackground(new java.awt.Color(255, 153, 51));
        navButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ButtonIcon.png"))); // NOI18N
        navButton.setContentAreaFilled(false);
        navButton.setDoubleBuffered(true);
        navButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navButtonActionPerformed(evt);
            }
        });

        mahasiswaText.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        mahasiswaText.setForeground(new java.awt.Color(255, 255, 255));
        mahasiswaText.setText("MAHASISWA");

        signOut.setBackground(new java.awt.Color(255, 255, 255));
        signOut.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        signOut.setForeground(new java.awt.Color(0, 0, 0));
        signOut.setText("Sign Out");
        signOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout orangePanelLayout = new javax.swing.GroupLayout(orangePanel);
        orangePanel.setLayout(orangePanelLayout);
        orangePanelLayout.setHorizontalGroup(
            orangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orangePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(navButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mahasiswaText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 654, Short.MAX_VALUE)
                .addComponent(signOut)
                .addGap(18, 18, 18))
        );
        orangePanelLayout.setVerticalGroup(
            orangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orangePanelLayout.createSequentialGroup()
                .addComponent(mahasiswaText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(orangePanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(orangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(signOut)
                    .addComponent(navButton))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pnlCards.setBackground(new java.awt.Color(255, 255, 255));
        pnlCards.setLayout(new java.awt.CardLayout());

        welcomePanel.setBackground(new java.awt.Color(255, 255, 255));
        welcomePanel.setMaximumSize(new java.awt.Dimension(960, 578));
        welcomePanel.setMinimumSize(new java.awt.Dimension(960, 578));
        welcomePanel.setName(""); // NOI18N
        welcomePanel.setPreferredSize(new java.awt.Dimension(960, 578));
        welcomePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        showName.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        showName.setForeground(new java.awt.Color(0, 0, 0));
        showName.setText("null");
        welcomePanel.add(showName, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 160, 270, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Welcome to the Electronic Mail");
        welcomePanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("(E-SURAT) of Mulawarman University");
        welcomePanel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        pnlCards.add(welcomePanel, "card2");

        suratPanel.setBackground(new java.awt.Color(255, 255, 255));
        suratPanel.setMaximumSize(new java.awt.Dimension(960, 578));
        suratPanel.setMinimumSize(new java.awt.Dimension(960, 578));
        suratPanel.setName(""); // NOI18N
        suratPanel.setPreferredSize(new java.awt.Dimension(960, 578));
        suratPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buatSuratButton.setBackground(new java.awt.Color(255, 153, 51));
        buatSuratButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buatSuratButton.setForeground(new java.awt.Color(255, 255, 255));
        buatSuratButton.setText("Buat Surat");
        buatSuratButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buatSuratButtonActionPerformed(evt);
            }
        });
        suratPanel.add(buatSuratButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 50, -1, -1));

        suratTabel.setBackground(new java.awt.Color(255, 255, 255));
        suratTabel.setForeground(new java.awt.Color(0, 0, 0));
        suratTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Jenis Surat", "Status", "Posisi Surat", "Aksi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        suratTabel.setToolTipText("");
        suratTabel.setFocusable(false);
        suratTabel.setGridColor(new java.awt.Color(204, 204, 204));
        suratTabel.setRowSelectionAllowed(false);
        suratTabel.setSelectionBackground(new java.awt.Color(255, 153, 102));
        suratTabel.setSelectionForeground(new java.awt.Color(204, 204, 204));
        suratTabel.setShowGrid(true);
        suratTabel.getTableHeader().setResizingAllowed(false);
        suratTabel.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(suratTabel);

        suratPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 620, 300));

        pnlCards.add(suratPanel, "card2");

        profilPanel.setBackground(new java.awt.Color(255, 255, 255));
        profilPanel.setMaximumSize(new java.awt.Dimension(892, 492));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Account Personal Information");

        saveData.setBackground(new java.awt.Color(255, 153, 51));
        saveData.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        saveData.setForeground(new java.awt.Color(255, 255, 255));
        saveData.setText("Save Data");
        saveData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveDataActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("First Name");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Last Name");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Study Program");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("GPA");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Phone Number");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Email");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Enrollment Year");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Semester");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Adress");

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Place of Birth");

        jLabel14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Date of Birth");

        dayCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        dayCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayComboActionPerformed(evt);
            }
        });

        monthCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        monthCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthComboActionPerformed(evt);
            }
        });

        yearCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023" }));
        yearCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearComboActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText("Study Level and Degree");

        javax.swing.GroupLayout profilPanelLayout = new javax.swing.GroupLayout(profilPanel);
        profilPanel.setLayout(profilPanelLayout);
        profilPanelLayout.setHorizontalGroup(
            profilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilPanelLayout.createSequentialGroup()
                .addGroup(profilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(profilPanelLayout.createSequentialGroup()
                        .addGap(595, 595, 595)
                        .addComponent(saveData))
                    .addGroup(profilPanelLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addGroup(profilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(studyProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel12)
                            .addGroup(profilPanelLayout.createSequentialGroup()
                                .addComponent(dayCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(monthCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yearCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel14)
                            .addComponent(addressPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studyLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel11)
                            .addComponent(semesterYear, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(profilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(gpaPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailUser, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(placeBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel4)
                            .addComponent(jLabel10)
                            .addComponent(enrollYear, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(phoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(205, 205, 205))
        );
        profilPanelLayout.setVerticalGroup(
            profilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5)
                .addGap(21, 21, 21)
                .addGroup(profilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(profilPanelLayout.createSequentialGroup()
                        .addGroup(profilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(profilPanelLayout.createSequentialGroup()
                                .addGroup(profilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(profilPanelLayout.createSequentialGroup()
                                        .addGroup(profilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(46, 46, 46)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(studyProgram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(profilPanelLayout.createSequentialGroup()
                                        .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(46, 46, 46)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(gpaPoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(12, 12, 12)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(studyLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(profilPanelLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(enrollYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(semesterYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(profilPanelLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(profilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profilPanelLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(placeBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(profilPanelLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(profilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dayCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(monthCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yearCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(profilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(profilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressPlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(saveData)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pnlCards.add(profilPanel, "card5");

        buatPanel.setBackground(new java.awt.Color(255, 255, 255));
        buatPanel.setMaximumSize(new java.awt.Dimension(960, 578));
        buatPanel.setMinimumSize(new java.awt.Dimension(960, 578));
        buatPanel.setName(""); // NOI18N
        buatPanel.setPreferredSize(new java.awt.Dimension(960, 578));
        buatPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pilihSurat.setBackground(new java.awt.Color(255, 255, 255));
        pilihSurat.setForeground(new java.awt.Color(0, 0, 0));
        pilihSurat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Surat Aktif Kuliah", "Surat Keterangan Berkelakuan baik", "Surat Keterangan Kehilangan KTM", "Surat Keterangan Tugas Akhir", "Surat Rekomendasi Beasiswa", "Surat Keterangan Cuti", "Surat keterangan Pengunduran Diri", "Transkrip Nilai Sementara" }));
        pilihSurat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        pilihSurat.setMaximumSize(new java.awt.Dimension(100, 100));
        pilihSurat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihSuratActionPerformed(evt);
            }
        });
        buatPanel.add(pilihSurat, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 470, -1));

        buatSurat.setBackground(new java.awt.Color(255, 153, 51));
        buatSurat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buatSurat.setForeground(new java.awt.Color(255, 255, 255));
        buatSurat.setText("Buat Surat");
        buatSurat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buatSuratActionPerformed(evt);
            }
        });
        buatPanel.add(buatSurat, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, -1, -1));

        peruntukanField.setBackground(new java.awt.Color(255, 255, 255));
        peruntukanField.setForeground(new java.awt.Color(0, 0, 0));
        peruntukanField.setText("Silahkan mengisi peruntukkan surat");
        peruntukanField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        peruntukanField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peruntukanFieldActionPerformed(evt);
            }
        });
        buatPanel.add(peruntukanField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 470, 70));

        pnlCards.add(buatPanel, "card2");

        hidePanel.setBackground(new java.awt.Color(255, 255, 255));
        hidePanel.setMaximumSize(new java.awt.Dimension(960, 578));
        hidePanel.setMinimumSize(new java.awt.Dimension(960, 578));
        hidePanel.setName(""); // NOI18N
        hidePanel.setPreferredSize(new java.awt.Dimension(960, 578));
        hidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        hidePanel.add(successfullyPop, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, -1));

        pnlCards.add(hidePanel, "card2");

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(Navigation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(pnlCards, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(orangePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(orangePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Navigation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlCards, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(background, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
        
    private int getMonthNumber(String month) throws java.text.ParseException {
        SimpleDateFormat monthParse = new SimpleDateFormat("MMMM", Locale.ENGLISH);
        Date date = null;
        date = monthParse.parse(month);
        Calendar cal = Calendar.getInstance();
        cal.setTime(date);
        return cal.get(Calendar.MONTH) + 1; // Adding 1 as months are zero-based in Calendar class
    }
    
     private void showData() {
        String nimToCheck = roleChecker;
        DataDiri dataMahasiswa = new DataDiri();
        String[] data = dataMahasiswa.readData(nimToCheck);
        
        String fullName = (String) data[1];
        String[] names = fullName.split("\\s", 2);
        if (data != null && data.length > 1) {
            
            if (names.length > 0) {
                firstName.setText(names[0]);
            }
            if (names.length > 1) {
                lastName.setText(" " + names[1]);
            }
            studyProgram.setText(data[2]);
            studyLevel.setText(data[3]);
            gpaPoint.setText(data[4]);
            phoneNumber.setText(data[5]);
            enrollYear.setText(data[6]);
            semesterYear.setText(data[7]);
            addressPlace.setText(data[8]);
            placeBirth.setText(data[10]);
            
            String[] dateComponents = data[11].split("-");
            if (dateComponents.length == 3) {
                String year = dateComponents[0];
                String month = dateComponents[1];
                String day = dateComponents[2];
                dayCombo.setSelectedItem(day);
                monthCombo.setSelectedItem(month);
                yearCombo.setSelectedItem(year);
            }
            
            emailUser.setText(data[12]);
        } else {
            System.out.println("Data tidak ditemukan");
        }
    }
    
    private void welcomePage() {
        String nimToCheck = roleChecker;
        DataDiri dataMahasiswa = new DataDiri();
        String[] data = dataMahasiswa.readData(nimToCheck);
        
        String fullName = (String) data[1];
        String[] names = fullName.split("\\s", 2);
            if (data != null && data.length > 1) {

                if (names.length > 0) {
                    firstName.setText(names[0]);
                }
                if (names.length > 1) {
                    lastName.setText(" " + names[1]);
                }
            showName.setText(names[0]);
        }
    }
     
    private void navigateToLoginScreen() {
        ChooseLogin loginScreen = new ChooseLogin();
        loginScreen.setVisible(true); 
        this.dispose();
    }
    
    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        cardLayout.show(pnlCards, "pnlCard1");
        welcomePage();
    }//GEN-LAST:event_homeActionPerformed

    private void suratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suratActionPerformed
        // TODO add your handling code here:
        cardLayout.show(pnlCards, "pnlCard3");
        showTable();
    }//GEN-LAST:event_suratActionPerformed

    private void navButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navButtonActionPerformed
        // TODO add your handling code here:
        Dimension currentSize = Navigation.getSize();

        if (currentSize.equals(new Dimension(50, 520))) {
            Navigation.setPreferredSize(new Dimension(110, 520));
        } else {
            Navigation.setPreferredSize(new Dimension(50, 520));
        }

        Navigation.revalidate();
        Navigation.repaint();
    }//GEN-LAST:event_navButtonActionPerformed

    private void buatSuratButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buatSuratButtonActionPerformed
        // TODO add your handling code here:
        cardLayout.show(pnlCards, "pnlCard4");
    }//GEN-LAST:event_buatSuratButtonActionPerformed

    private void pilihSuratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihSuratActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pilihSuratActionPerformed

    private void buatSuratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buatSuratActionPerformed
        // TODO add your handling code here:
        String selectedSurat = (String) pilihSurat.getSelectedItem();
        String posisiSurat;
        String action = "Detail";
        if (selectedSurat != null) {
            if (selectedSurat.equals("Surat Aktif Kuliah") || selectedSurat.equals("Surat Keterangan Berkelakuan baik") || selectedSurat.equals("Surat KETERANGAN KEHIlangan KTM") || selectedSurat.equals("Surat Keterangan Tugas Akhir")) {
                posisiSurat = "Staff Kemahasiswaan";
            } else {
                posisiSurat = "Staff Akademik";
            }
            
            Pengajuan pengajuanSurat = new Pengajuan(peruntukanField.getText(), mahasiswaNIM, roleChecker);
            String idPengajuan = pengajuanSurat.insertData();

            if (idPengajuan != null) {
                RiwayatSurat riwayatSurat = new RiwayatSurat();

                boolean insertSuccessful = riwayatSurat.insertData(selectedSurat, posisiSurat, action, idPengajuan);

                if (insertSuccessful) {
                    System.out.println("Inserted: " + selectedSurat);
                    cardLayout.show(pnlCards, "pnlCard2");
                    showTable();
                    JButton detailButton = new JButton("Detail: " + selectedSurat);
                    detailButton.addActionListener((ActionEvent e) -> {
                        JOptionPane.showMessageDialog(null, "Displaying details for: " + selectedSurat);
                    });
                    
                    suratButtonPanel.add(detailButton);
                    suratButtonPanel.revalidate();
                    suratButtonPanel.repaint();
                } else {
                    System.out.println("Failed to insert: " + selectedSurat);
                }
            } else {
                System.out.println("Failed to obtain ID_Pengajuan");
            }
        }
    }//GEN-LAST:event_buatSuratActionPerformed
   
    private void peruntukanFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peruntukanFieldActionPerformed
        // TODO add your handling code here:
        String userPeruntukanInput = peruntukanField.getText();

        if (userPeruntukanInput != null && !userPeruntukanInput.isEmpty()) {
            System.out.println("User input for Peruntukan: " + userPeruntukanInput);
        } else {
            System.out.println("Data tidak ditemukan");
        }
    }//GEN-LAST:event_peruntukanFieldActionPerformed
    
    private void signOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOutActionPerformed
        // TODO add your handling code here:
        navigateToLoginScreen();
    }//GEN-LAST:event_signOutActionPerformed
    
    private void saveDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveDataActionPerformed
        try {
            String nimToCheck = roleChecker;
            System.out.println("Button Clicked!");
            DataDiri dataMahasiswa = new DataDiri();
            String[] data = dataMahasiswa.readData(nimToCheck);
       
            String textFirstName = firstName.getText();
            String textLastName = lastName.getText();
            String updatedAlamat = addressPlace.getText();
            String updatedProgram = studyProgram.getText();
            String updatedJenjang = studyLevel.getText();
            String updatedIpk = gpaPoint.getText();
            String updatedKontak = phoneNumber.getText();
            String updatedAngkatan = enrollYear.getText();
            String updatedSemester = semesterYear.getText();
            String updatedTempatLahir = placeBirth.getText();
            
            String updatedEmail = emailUser.getText();
            
            String selectedYear = yearCombo.getSelectedItem().toString();
            String selectedMonth = monthCombo.getSelectedItem().toString();
            String selectedDay = dayCombo.getSelectedItem().toString();
            String formattedDate = String.format("%s-%02d-%02d", selectedYear, getMonthNumber(selectedMonth), Integer.parseInt(selectedDay));
            String updatedTTL = formattedDate;
            String updatedFullName = textFirstName + textLastName;
            
            DataUpdate dataUpdate = new DataUpdate(nimToCheck,updatedFullName, updatedAlamat, selectedYear, selectedMonth, selectedDay, updatedAngkatan, updatedIpk, updatedProgram, updatedJenjang, updatedKontak, updatedSemester, updatedTempatLahir, updatedEmail, updatedTTL);
            
            boolean updateSuccessful = dataMahasiswa.updateData(dataUpdate);
            if (updateSuccessful) {
                System.out.println("Data updated successfully!");
                JOptionPane.showMessageDialog(this, "Data updated successfully!");
            } else {
                System.out.println("Failed to update data.");
            }
        } catch (java.text.ParseException ex) {
            Logger.getLogger(MahasiswaInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveDataActionPerformed

    private void dayComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dayComboActionPerformed

    private void monthComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthComboActionPerformed

    private void yearComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearComboActionPerformed

    private void profilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilActionPerformed
        // TODO add your handling code here:
        cardLayout.show(pnlCards, "pnlCard2");
    }//GEN-LAST:event_profilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MahasiswaInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MahasiswaInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MahasiswaInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MahasiswaInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            MahasiswaInterface mahasiswaInterface = new MahasiswaInterface("roleChecker");
            mahasiswaInterface.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Navigation;
    private javax.swing.JTextField addressPlace;
    private javax.swing.JPanel background;
    private javax.swing.JPanel buatPanel;
    private javax.swing.JButton buatSurat;
    private javax.swing.JButton buatSuratButton;
    private javax.swing.JComboBox<String> dayCombo;
    private javax.swing.JTextField emailUser;
    private javax.swing.JTextField enrollYear;
    private javax.swing.JTextField firstName;
    private javax.swing.JTextField gpaPoint;
    private javax.swing.JPanel hidePanel;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastName;
    private javax.swing.JLabel mahasiswaText;
    private javax.swing.JComboBox<String> monthCombo;
    private javax.swing.JButton navButton;
    private javax.swing.JPanel orangePanel;
    private javax.swing.JTextField peruntukanField;
    private javax.swing.JTextField phoneNumber;
    private javax.swing.JComboBox<String> pilihSurat;
    private javax.swing.JTextField placeBirth;
    private javax.swing.JPanel pnlCards;
    private javax.swing.JButton profil;
    private javax.swing.JPanel profilPanel;
    private javax.swing.JButton saveData;
    private javax.swing.JTextField semesterYear;
    private javax.swing.JLabel showName;
    private javax.swing.JButton signOut;
    private javax.swing.JTextField studyLevel;
    private javax.swing.JTextField studyProgram;
    private javax.swing.JOptionPane successfullyPop;
    private javax.swing.JButton surat;
    private javax.swing.JPanel suratPanel;
    private javax.swing.JTable suratTabel;
    private javax.swing.JPanel welcomePanel;
    private javax.swing.JComboBox<String> yearCombo;
    // End of variables declaration//GEN-END:variables

}
