package gui;

import database.Database;
import java.awt.Color;
import entitas.Admin;

public class StaffForm extends javax.swing.JFrame {
    final Database database;
    
    public StaffForm() {
        initComponents();
        database = new Database();
        passTextField.setEchoChar((char) 0);
        passTextField.setText("Password");
        popError.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background1 = new javax.swing.JPanel();
        unmulIcon = new javax.swing.JLabel();
        popError = new javax.swing.JTextArea();
        frameName = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        emailTextField = new javax.swing.JTextField();
        passTextField = new javax.swing.JPasswordField();
        signButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background1.setBackground(new java.awt.Color(204, 204, 204));
        background1.setMinimumSize(new java.awt.Dimension(300, 300));
        background1.setName(""); // NOI18N
        background1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        unmulIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        unmulIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Unmul-Icon.png"))); // NOI18N
        background1.add(unmulIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 390, 140));

        popError.setEditable(false);
        popError.setBackground(new java.awt.Color(221, 75, 57));
        popError.setColumns(20);
        popError.setRows(5);
        popError.setText("nim tidak boleh kosong\npassword tidak boleh kosong");
        popError.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 6, 6, 6));
        popError.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        background1.add(popError, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 330, 40));

        frameName.setEditable(false);
        frameName.setBackground(new java.awt.Color(255, 255, 255));
        frameName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        frameName.setForeground(new java.awt.Color(0, 0, 51));
        frameName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        frameName.setText("E-Surat Fakultas Teknik UNMUL");
        frameName.setBorder(null);
        background1.add(frameName, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 220, 370, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        emailTextField.setBackground(new java.awt.Color(255, 255, 255));
        emailTextField.setForeground(new java.awt.Color(204, 204, 204));
        emailTextField.setText("Nim");
        emailTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        emailTextField.setName("nim"); // NOI18N
        emailTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailTextFieldFocusLost(evt);
            }
        });
        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(emailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 330, 40));

        passTextField.setBackground(new java.awt.Color(255, 255, 255));
        passTextField.setText("Password");
        passTextField.setActionCommand("<Not Set>");
        passTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        passTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passTextFieldFocusLost(evt);
            }
        });
        passTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(passTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 330, 40));

        signButton.setBackground(new java.awt.Color(51, 153, 255));
        signButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        signButton.setForeground(new java.awt.Color(255, 255, 255));
        signButton.setText("Sign In");
        signButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        signButton.setBorderPainted(false);
        signButton.setRequestFocusEnabled(false);
        signButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signButtonActionPerformed(evt);
            }
        });
        jPanel1.add(signButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 330, 40));

        background1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 390, 500));

        getContentPane().add(background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
       
    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void emailTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTextFieldFocusGained
        // TODO add your handling code here:
        if (emailTextField.getText().equals("Nim")) {
        emailTextField.setText("");
        emailTextField.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_emailTextFieldFocusGained

    private void emailTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTextFieldFocusLost
        // TODO add your handling code here:
        if (emailTextField.getText().isEmpty()) {
        emailTextField.setText("Nim");
        emailTextField.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_emailTextFieldFocusLost

    private void passTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passTextFieldActionPerformed

    private void passTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passTextFieldFocusGained
        // TODO add your handling code here:
        if (new String(passTextField.getPassword()).equals("Password")) {
        passTextField.setText("");
        passTextField.setEchoChar('*');
        emailTextField.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_passTextFieldFocusGained

    private void passTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passTextFieldFocusLost
        // TODO add your handling code here:
        if (new String(passTextField.getPassword()).isEmpty()) {
        passTextField.setText("Password");
        passTextField.setEchoChar((char) 0);
        emailTextField.setForeground(Color.GRAY);
        
        }
    }//GEN-LAST:event_passTextFieldFocusLost

    private void signButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signButtonActionPerformed
        // TODO add your handling code here:
        String email = emailTextField.getText();
        String password = new String(passTextField.getPassword());

        if (email.equals("Email") || password.isEmpty()) {
            popError.setText("• Email tidak boleh kosong\n• Password tidak boleh kosong");
            popError.setVisible(true);
        } else {
            Admin data = new Admin (email,password);
            data.openConnection();

            if (data.readData()) {
                StaffInterface staffInterface = new StaffInterface(email);
                staffInterface.setVisible(true);
                popError.setVisible(false);
                this.dispose();
            } else {
                popError.setText("• Login gagal, silahkan cek kembali nim dan password");
                popError.setVisible(true);
            }

            data.closeConnection();
        }
    }//GEN-LAST:event_signButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new StaffForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background1;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JTextField frameName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField passTextField;
    private javax.swing.JTextArea popError;
    private javax.swing.JButton signButton;
    private javax.swing.JLabel unmulIcon;
    // End of variables declaration//GEN-END:variables
}
